//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleadmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orders = new HashSet<cart>();
        }
        [DisplayName("Product Id")]

        public int p_id { get; set; }
        [DisplayName("Product Name")]

        public string pname { get; set; }
        [DisplayName("Image")]
        public string p_image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [DisplayName("Product Price")]

        public Nullable<int> price { get; set; }
        [DisplayName("Product Description")]

        public string description { get; set; }
        [DisplayName("Category")]

        public Nullable<int> cat_id { get; set; }
        [DisplayName("Admin")]

        public Nullable<int> aid { get; set; }

        public virtual admin admin { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> orders { get; set; }
    }
}